// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWYfcXc5Ns4U937SxL1GaCHBvcUw6eho0',
    appId: '1:731944079598:web:82cdd3136522d23b2b23ff',
    messagingSenderId: '731944079598',
    projectId: 'worklo-4664a',
    authDomain: 'worklo-4664a.firebaseapp.com',
    storageBucket: 'worklo-4664a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUYdZsWgetmYESO8MuqTy_PMa7k24slqY',
    appId: '1:731944079598:android:c26141040cfd58062b23ff',
    messagingSenderId: '731944079598',
    projectId: 'worklo-4664a',
    storageBucket: 'worklo-4664a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTOZhaMo6TdD9BxygxLGTZn9nWXixDvUk',
    appId: '1:731944079598:ios:5b34fd663a06ad6f2b23ff',
    messagingSenderId: '731944079598',
    projectId: 'worklo-4664a',
    storageBucket: 'worklo-4664a.appspot.com',
    iosBundleId: 'com.example.worklo',
  );
}
